Move code
abf7d/render pull request #1
Opened 2022-11-10 15:30 UTC by s-n-i

2022-11-15 15:25 UTC, abf7d requested changes

2022-11-15 15:25 UTC, abf7d commented on apps/render-ui/src/app/app.component.ts
> +            'https://vast-sands-14867.herokuapp.com/https://tripod.nih.gov/servlet/renderServletv16?background=transparent&format=png&structure=',
Bring this url in through a config file.  Have a file `constants.ts`, add this string to it, import it at the top of the file, then use it here.

2022-11-15 15:25 UTC, abf7d commented on libs/data-processing/process-overlay-data.ts
> +            ].gridCellLayers.reduce((acc: any, entry: any) => ({...acc, [entry.id]: entry.data[j].fillColor}), {} /*, {
remove commented code

2022-11-15 15:25 UTC, abf7d commented on libs/layers/generateHeatmap.ts
> +    //visible,
remove commented code

2022-11-15 15:25 UTC, abf7d commented on libs/ui/src/lib/image-menu/image-menu-web-component.ts
> +                pixelValuesContainer.innerHTML=currentState.pixelValues.slice(0,numberOfChannels).map((value:[])=>`<div style="margin-top:91px;">${value}</div>`).join("");
Is there a way to format this better? It doesn't look like linting is working

2022-11-15 15:25 UTC, abf7d commented on libs/ui/src/lib/image-menu/image-menu-web-component.ts
> +                        </select>
Is there a way to format this better? It doesn't look like linting is working

2022-11-15 15:25 UTC, abf7d commented on libs/ui/src/lib/image-menu/image-menu-web-component.ts
> +                    const unsubscribeViewerStore = useViewerStore.subscribe((currentViewerStoreState: any, previousViewerStoreState: any)=>{
Is there a way to format this better? It doesn't look like linting is working

2022-11-15 15:25 UTC, abf7d commented on libs/ui/src/lib/image-menu/multi-range-slider-web-component.ts
> +                right: 15px;
is there a way to import these styles from a file?

2022-11-15 15:25 UTC, abf7d commented on libs/ui/src/lib/image-menu/multi-range-slider-web-component.ts
> +  var children = this.parentNode.childNodes[1].childNodes;
use let or const instead of var

2022-11-15 15:25 UTC, abf7d commented on libs/ui/src/lib/image-menu/multi-range-slider-web-component.ts
> +  children[3].style.width=(100-value)+'%';
use let or const instead of var

2022-11-15 15:25 UTC, abf7d commented on libs/ui/src/lib/overlay-menu/OverlayMenu.component.html
> +-->
Remove commented code, rename file to `overlay-menu.component.html`

2022-11-15 15:25 UTC, abf7d commented on libs/ui/src/lib/overlay-menu/OverlayMenu.component.ts
> +  @ViewChild("overlayMenuVIewChild") overlayMenuVIewChild: any;
Remove commented code

2022-11-15 15:25 UTC, abf7d commented on libs/ui/src/lib/overlay-menu/OverlayMenu.component.ts
> +    this.overlayMenuVIewChild.nativeElement.data=changes.heatmapIds.currentValue;
remove console.log

2022-11-15 15:25 UTC, abf7d commented on libs/ui/src/lib/overlay-menu/OverlayMenuWebComponent.ts
> +                    <input class="form-check-input" type="checkbox" ${value ? "checked" : ""} value=${`"${key}"`} onclick="this.getRootNode().host.handleClick(this)">
Lint this code or use a line break and indents so this is more readable. rename file to overly-menu-web-component.ts

2022-11-15 15:25 UTC, abf7d commented on libs/ui/src/lib/overlay-menu/OverlayMenuWebComponent.ts
> +            </div>
Add line breaks / indents here

2022-11-15 15:25 UTC, abf7d commented on libs/viv-viewer/src/lib/Avivator/src/Avivator.jsx
Remove commented code

2022-11-15 15:25 UTC, abf7d commented on libs/viv-viewer/src/lib/Avivator/src/Avivator.jsx
> +      {!isViewerLoading && <Viewer urls={urls} processedData={processedData} heatmapId={heatmapId} heatmapOpacity={heatmapOpacity} overlayVisibilities={overlayVisibilities}/>}
add line breaks / indents

2022-11-15 15:25 UTC, abf7d commented on libs/viv-viewer/src/lib/Avivator/src/hooks.js
> +        );*/
removed commented code

2022-11-15 15:25 UTC, abf7d commented on apps/render-ui/src/app/app.component.html
> +-->
Remove commented code

2022-11-15 18:37 UTC, s-n-i commented
Rename libs/viv-viewer/src/lib/Avivator/src/index.jsx to viv-viewer-web-component.jsx

2022-11-15 18:37 UTC, s-n-i commented
Add padding to Add Channel button

2022-11-15 18:39 UTC, s-n-i commented
Rename ui to menu-compoentns

2022-11-16 15:23 UTC, s-n-i commented
Delete unused files

2022-11-16 15:39 UTC, s-n-i commented
Add angular library that wraps menus and viewer, and have the app consume it

2022-11-17 22:06 UTC, abf7d requested changes

2022-11-17 22:06 UTC, abf7d commented on libs/ui/src/lib/overlay-menu/overlay-menu.component.ts
> +    console.log(changes, 'changes',this.overlayMenuVIewChild.nativeElement)
Removed console.log

2022-11-17 22:06 UTC, abf7d commented on libs/views/src/lib/viv-view/viv-view.component.html
> +<div style='position: fixed; z-index: 10; margin-right: "8px"; right: 0; top:0; width: "365px"; padding-bottom: "12px"; background-color: rgba(0, 0, 0, 0.75)'>
Move inline styles to stylesheet

2022-11-17 22:06 UTC, abf7d commented on libs/views/src/lib/viv-view/viv-view.component.ts
> +    //this.heatmapIds=value;
Remove commented code

2022-11-17 22:06 UTC, abf7d commented on libs/views/src/lib/viv-view/viv-view.component.ts
> +    //this.heatmapIds=value;
Remove commented code and console.log

2022-11-17 22:06 UTC, abf7d commented on libs/views/src/lib/viv-view/viv-view.component.ts
> +    console.log('overlayData',value)
remove commented code and console.log

2022-11-18 15:38 UTC, s-n-i commented
Add Husky to run the linter as a pre-commit hook

2022-11-18 15:41 UTC, abf7d requested changes

2022-11-18 15:41 UTC, abf7d commented on libs/viv-viewer/src/lib/Avivator/src/components/Viewer.jsx
> +  */
Remvoed commented code

2022-11-18 15:41 UTC, abf7d commented on libs/viv-viewer/src/index.ts
>  // export * from './lib/viv-viewer-web-comp-wrapper.jsx';
remove commented code

2022-11-23 18:45 UTC, abf7d requested changes

2022-11-23 18:45 UTC, abf7d commented on libs/viv-viewer/src/lib/Avivator/src/viv-viewer-web-component.jsx
> +    //const root = this.attachShadow({ mode: 'open' });
remove commented code

2022-11-29 21:16 UTC, merged